# Generated by Django 5.2.15 on 2026-06-16 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('moral', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hi', 'Hindi'), ('de', 'German'), ('ja', 'Japanese')], default='en', max_length=10)),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('adventure', 'Adventure'), ('mystery', 'Mystery'), ('sci_fi', 'Science Fiction'), ('fairy_tale', 'Fairy Tale'), ('historical', 'Historical'), ('humor', 'Humor'), ('horror', 'Horror')], default='fantasy', max_length=20)),
                ('age_group', models.CharField(choices=[('3-5', '3–5 years'), ('6-8', '6–8 years'), ('9-12', '9–12 years'), ('13-17', '13–17 years'), ('18+', '18+ years')], default='6-8', max_length=10)),
                ('prompt', models.TextField(blank=True)),
                ('audio_converted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
