# Generated by Django 5.2.15 on 2026-06-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='audio_source',
            field=models.CharField(choices=[('elevenlabs', 'ElevenLabs'), ('demo', 'Demo')], default='demo', max_length=20),
        ),
    ]
