# Generated by Django 5.2.15 on 2026-06-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0002_audiobook_audio_file_audiobook_audio_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='music_style',
            field=models.CharField(blank=True, default='none', max_length=30),
        ),
    ]
