# Generated by Django 5.2.15 on 2026-06-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0003_audiobook_music_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='background_music_file',
            field=models.FileField(blank=True, upload_to='audio/music/'),
        ),
    ]
