# Generated by Django 5.2.15 on 2026-06-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0004_audiobook_background_music_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='status_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
