# Generated by Django 5.2.15 on 2026-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksummary',
            name='chapter_short_summaries',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='booksummary',
            name='reading_guide',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booksummary',
            name='detailed_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booksummary',
            name='short_summary',
            field=models.TextField(blank=True),
        ),
    ]
